name: CI with Java and Gradle

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup Java

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Checkout our code
        uses: actions/checkout@v2

      # Make Gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Run our build using gradle
      - name: Build with Gradle
        run: ./gradlew build

      #Publish JavaDoc
      
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          java-version: 17

